#!/usr/bin/env node
/**
 * Downloads the faces described in lib/fontSpec.js into public/fonts and
 * writes styles/fonts.css to match. Re-run after editing the spec.
 *
 * The User-Agent matters: Google serves woff2 only to a UA it recognises, so
 * this asks as a current desktop Chrome and refuses anything that is not
 * woff2 rather than quietly self-hosting the 2x-larger legacy format.
 */
import { writeFile, mkdir, readdir, unlink } from 'node:fs/promises';
import path from 'node:path';
import url from 'node:url';
import { FONT_REQUESTS } from '../lib/fontSpec.js';

const ROOT = path.join(path.dirname(url.fileURLToPath(import.meta.url)), '..');
const FONT_DIR = path.join(ROOT, 'public', 'fonts');
const CSS_OUT = path.join(ROOT, 'styles', 'fonts.css');
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

function parseFontFaces(css) {
  const faces = [];
  const re = /(?:\/\*\s*([^*]+?)\s*\*\/\s*)?@font-face\s*\{([\s\S]*?)\}/g;
  for (const [, subset, body] of css.matchAll(re)) {
    const pick = (k, p = "[^;]+") => (body.match(new RegExp(`${k}:\\s*(${p})\\s*;`)) || [])[1]?.trim();
    const src = (body.match(/url\((https:[^)]+)\)/) || [])[1];
    if (!src) continue;
    faces.push({
      subset: (subset || 'custom').trim(),
      family: pick('font-family')?.replace(/'/g, ''),
      weight: pick('font-weight'),
      style: pick('font-style'),
      unicodeRange: pick('unicode-range'),
      src,
    });
  }
  return faces;
}

await mkdir(FONT_DIR, { recursive: true });

const collected = [];
for (const req of FONT_REQUESTS) {
  const href = `https://fonts.googleapis.com/css2?family=${req.query}${req.text ? `&text=${encodeURIComponent(req.text)}` : ''}&display=swap`;
  const res = await fetch(href, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${req.label}: Google returned ${res.status}`);
  const faces = parseFontFaces(await res.text());
  if (faces.length === 0) throw new Error(`${req.label}: no @font-face blocks parsed`);

  // A variable family answers every weight with the same file, so group by
  // source URL first. Downloading per weight wrote four byte-identical
  // copies of DM Sans — 244KB of the same 61KB variable font.
  const byUrl = new Map();
  for (const face of faces) {
    if (!byUrl.has(face.src)) byUrl.set(face.src, []);
    byUrl.get(face.src).push(face);
  }

  for (const [src, group] of byUrl) {
    if (!src.endsWith('.woff2') && !src.includes('/l/font?kit=')) {
      throw new Error(`${req.label}: expected woff2, got ${src}`);
    }
    const weights = [...new Set(group.map(f => Number(f.weight)))].sort((a, b) => a - b);
    const variable = weights.length > 1;
    const { subset, family, style, unicodeRange } = group[0];
    const file = variable
      ? `${req.label}-${subset}.woff2`
      : `${req.label}-${weights[0]}-${subset}.woff2`;

    const bin = await fetch(src, { headers: { 'User-Agent': UA } });
    if (!bin.ok) throw new Error(`${file}: download returned ${bin.status}`);
    const buf = Buffer.from(await bin.arrayBuffer());
    // woff2 files start with the signature 'wOF2'.
    if (buf.subarray(0, 4).toString('latin1') !== 'wOF2') {
      throw new Error(`${file}: not a woff2 (got ${buf.subarray(0, 4).toString('latin1')}) — Google served a legacy format`);
    }
    await writeFile(path.join(FONT_DIR, file), buf);

    collected.push({
      file,
      family,
      style,
      unicodeRange,
      // One ranged rule for a variable face, rather than four identical
      // blocks that differ only in the weight they claim.
      weight: variable ? `${weights[0]} ${weights.at(-1)}` : String(weights[0]),
      bytes: buf.length,
    });
  }
}

// Drop files from a previous run that the current spec no longer produces.
const keep = new Set(collected.map(f => f.file));
for (const existing of await readdir(FONT_DIR)) {
  if (existing.endsWith('.woff2') && !keep.has(existing)) {
    await unlink(path.join(FONT_DIR, existing));
    console.log(`  removed stale ${existing}`);
  }
}

const css = [
  '/* GENERATED by scripts/fetch_fonts.mjs — do not edit by hand.',
  ' * Edit lib/fontSpec.js and re-run `node scripts/fetch_fonts.mjs`. */',
  '',
  ...collected.map(f => [
    '@font-face {',
    `  font-family: '${f.family}';`,
    `  font-style: ${f.style};`,
    `  font-weight: ${f.weight};`,
    '  font-display: swap;',
    `  src: url('/fonts/${f.file}') format('woff2');`,
    ...(f.unicodeRange ? [`  unicode-range: ${f.unicodeRange};`] : []),
    '}',
  ].join('\n')),
  '',
].join('\n');
await writeFile(CSS_OUT, css);

const total = collected.reduce((n, f) => n + f.bytes, 0);
for (const f of collected) console.log(`✔ ${f.file.padEnd(38)} ${(f.bytes / 1024).toFixed(1).padStart(6)} KB`);
console.log(`\n${collected.length} faces, ${(total / 1024).toFixed(1)} KB total → public/fonts, styles/fonts.css`);
